#!/bin/sh

CUR_DIR=`pwd`

usage() {
    echo "Usage: $0 version"
}

CONFIGURE_OPTIONS=""
TARGET_VERSION="7.4"

while getopts hc: OPT
do
    case $OPT in
        h)  usage
            exit
            ;;
        c)
            CONFIGURE_OPTIONS="$OPTARG"
            ;;
        \?) usage
            exit
            ;;
    esac
done

# command
if [ "$1" = "install" -o "$1" = "build" -o "$1" = "clean" ]; then
    COMMAND=$1
    if [ "$2" != "" ];then
        TARGET_VERSION=$2
    fi
elif [ "$1" = "versions" ];then
    COMMAND=$1
    TARGET_VERSION=""
else
    COMMAND="install"
    if [ "$1" != "" ];then
        TARGET_VERSION=$1
    fi
fi

FILE_VERSIONS_LIST=".versions"
ARCH="unix"
ARC_DIR="$CUR_DIR/vim"
FTP_VIM_PATH="pub/vim"
SRC_ARC_URL_PATH="ftp://ftp.vim.org/$FTP_VIM_PATH/$ARCH"

if [ "$TARGET_VERSION" != "" ];then
    SRC_DIR="$CUR_DIR/build/$TARGET_VERSION"
    PATCH_DIR="$CUR_DIR/patches/$TARGET_VERSION"
    SRC_ARC_FILENAME="vim-"$TARGET_VERSION".tar.bz2"
else
    SRC_DIR=""
    PATCH_DIR=""
    SRC_ARC_FILENAME=""
fi

if [ "$CONFIGURE_OPTIONS" = "" ];then
    CONFIGURE_OPTIONS="\
 --enable-multibyte     \
 --with-features=huge   \
 --disable-selinux      \
 --prefix=/usr/local"
fi

# vim source download
download_vim_source() {
    cd $CUR_DIR
    mkdir -p $ARC_DIR
    cd $ARC_DIR
    curl -O $SRC_ARC_URL_PATH/$SRC_ARC_FILENAME
}

get_version() {
    cd $CUR_DIR
    ftp -n -i  <<EOF
open ftp.vim.org
user anonymous pass
cd $FTP_VIM_PATH/$ARCH
pwd
nlist vim-* $FILE_VERSIONS_LIST
bye
EOF
}

disp_version() {
    cd $CUR_DIR
    grep -v ".diff." $FILE_VERSIONS_LIST | cut -d"." -f1-2 | cut -d"-" -f2-
}

# patch download
download_patch() {
    cd $CUR_DIR
    mkdir -p $PATCH_DIR
    cd $PATCH_DIR
    ftp -n -i  <<EOF
open ftp.vim.org
user anonymous pass
cd $FTP_VIM_PATH/patches/$TARGET_VERSION
pwd
mget $TARGET_VERSION.*
bye
EOF
}

uncompress_vim_source() {
    cd $CUR_DIR
    rm -fr $SRC_DIR
    mkdir -p $SRC_DIR
    cd $SRC_DIR
    tar -xvjf $ARC_DIR/$SRC_ARC_FILENAME
}

# run patch
run_patch() {
    cd $PATCH_DIR
    patchlist=`ls -v $TARGET_VERSION.*`
    cd $SRC_DIR
    SRC_CORE_DIR=`ls | grep vim`
    cd $SRC_CORE_DIR
    for patchfile in $patchlist; do
        cat $PATCH_DIR/$patchfile
    done | patch -p0
}

# configure
run_configure() {
    cd $SRC_CORE_DIR
    ./configure $CONFIGURE_OPTIONS
}

# make
build_vim() {
    cd $SRC_CORE_DIR
    make clean
    make
}

command_clean() {
    cd $CUR_DIR
    rm -fr \
 $CUR_DIR/build/$TARGET_VERSION \
 $CUR_DIR/patches/$TARGET_VERSION
}

if [ "$COMMAND" = "clean" ];then
    command_clean
    exit
fi

if [ "$COMMAND" = "versions" ];then
    get_version
    disp_version
    exit
fi

if [ "$COMMAND" = "install" ];then
    get_version
    command_clean
    download_vim_source
    download_patch
    uncompress_vim_source
    run_patch
    run_configure
    build_vim
elif [ "$COMMAND" = "build" ];then
    uncompress_vim_source
    run_patch
    run_configure
    build_vim
fi

echo "To use this vim, do 'export PATH=$SRC_DIR/$SRC_CORE_DIR/bin:\$PATH'."
